### ISSUE TITLE
Question related to map in raspimouse_ros2.

### ISSUE THREAD

**Issue by jhbirdchoi** [youtalk/raspimouse_ros2#6]
Nice to meet you.
I want to use ros2 + rpi lidar + cartographer.
So I am doing it by referring to your data.

S/W  & H/W environment
.Ubuntu 18.04 + ros2 dashing version
.Rpi Lidar

I am trying to use slam(cartographer.) on ubuntu pc.
We proceeded in the following order.

Package build for PC

1. raspimouse_ros2 build
mkdir -p ~/ros/dashing/src
cd ~/ros/dashing/src
git clone https://github.com/youtalk/raspimouse_ros2.git
cd raspimouse_ros2
git submodule update --init
cd ../..
rosdep install --from-paths src --ignore-src -r -y
colcon build --symlink-install
source ~/ros/dashing/install/setup.bash

#ros2 launch raspimouse_bringup robot.launch.py

2. Run Rviz2.
#ros2 launch raspimouse_bringup rviz2.launch.py

The following error occurred.
---------------------------------------
Frame [odom] does not exist -> Global Status Error
[rviz2-1][ERROR][rviz2]: “odom” passed to lookupTransform argument target_grame does not exist.
---------------------------------------
Solution: Change the Fixed Frame and select base_link

3. Run raspimouse_cartographer to generate 2D map.
#ros2 launch raspimouse_cartographer cartographer.launch.py
The following error occurred.
---------------------------------------
Global Status: Error
Fixed Frame: Frame[map] does not exist.
---------------------------------

Please advise on which part to check.

Thank you.
thanks

**Comment by youtalk** [comment]
Please try the following command if you have no map.

```
ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0  map odom
```

**Comment by jhbirdchoi** [comment]
> Please try the following command if you have no map.
> 
> ```
> ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0  map odom
> ```

Thank you very much.
Your writing is really helpful.
thanksl

**Comment by nedo99** [comment]
Hi,

I have the similar issue, except I am not getting the error, just a warning that map is not received. I am getting `/scan` topic and I can see it in rviz, but no map.

I ran both:
`ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0  map odom`
and
`ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0  map laser_frame`

I am using your bag file from this repo: https://github.com/youtalk/raspimouse_bags/tree/master/raspimouse_slam.bag

My OS: Ubuntu 18.04
ROS Eloquent.

Regards,
Nedim

**Comment by youtalk** [comment]
Please do not call the following command. I think it's not correct.

> ```
> ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 map laser_frame
> ```

**Comment by nedo99** [comment]
Of course I tried without it, but then I dont even get the `/scan` data. Rviz2 reports:
` [rviz2]: Message Filter dropping message: frame 'laser_frame' at time 1567151496.241 for reason 'Unknown'`
